# Netlify configuration for Jekyll site
[build]
  command = "chmod +x prebuild.sh && ./prebuild.sh && bundle update && bundle install && bundle exec jekyll build"
  publish = "_site"

[build.environment]
  RUBY_VERSION = "2.7.2"

# Redirect default Netlify subdomain to primary domain
[[redirects]]
  from = "https://exocore-2.netlify.app/*"
  to = "https://<your-domain>.com/:splat"
  status = 301
  force = true 