[build]
  command = "chmod +x build.sh && ./build.sh"
  publish = "_site"

[build.environment]
  JEKYLL_ENV = "production"
  RUBY_VERSION = "2.7.2"

[[plugins]]
  package = "@netlify/plugin-sitemap"

# Redirect default Netlify subdomain to primary domain
[[redirects]]
  from = "https://exocore-2.netlify.app/*"
  to = "https://<your-domain>.com/:splat"
  status = 301
  force = true 