[build]
  command = "chmod +x netlify-build.sh && ./netlify-build.sh"
  publish = "_site"

[build.environment]
  NETLIFY_USE_YARN = "true"
  NODE_VERSION = "16"
  RUBY_VERSION = "false"

[[plugins]]
  package = "@netlify/plugin-sitemap"

# Redirect default Netlify subdomain to primary domain
[[redirects]]
  from = "https://exocore-2.netlify.app/*"
  to = "https://<your-domain>.com/:splat"
  status = 301
  force = true 