# Completely bypass Netlify's default bundler processing
[build]
  publish = "_site"
  ignore = "false"

# Use a custom build plugin to handle the Jekyll build process
[[plugins]]
  package = "@netlify/plugin-functions"

[[plugins]]
  package = "netlify-plugin-jekyll-build"
  
  [plugins.inputs]
    jekyllVersion = "4.2.1"
    skipBundleInstall = false
    skipRubySetup = false
    buildCommand = "rm -f Gemfile.lock && bundle _2.1.4_ update && bundle _2.1.4_ install --no-deployment && bundle _2.1.4_ exec jekyll build"
    installCommand = "bundle update && bundle _2.1.4_ install"

# Redirect default Netlify subdomain to primary domain
[[redirects]]
  from = "https://exocore-2.netlify.app/*"
  to = "https://<your-domain>.com/:splat"
  status = 301
  force = true 